version: '3'

tasks:
  check:
    desc: Check formatting
    cmds:
      - clang-format -n -Werror $(find src -name '*.cpp' -o -name '*.hpp')
      - python update.py --check

  fix:
    desc: Fix formatting in place
    cmds:
      - clang-format -i $(find src -name '*.cpp' -o -name '*.hpp')

  update:
    desc: Update the generated files
    cmds:
      - python update.py
